spring:
  application:
    name: g24
  datasource:
    url: jdbc:postgresql://localhost:5432/G24
    username: postgres
    password: 8aiMehrI
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  mail:
    host: smtp.sendgrid.net
    port: 587
    username: apikey
    password: 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
    from: g-24@bluewin.ch
    cc-email: mirzajahic1@hotmail.com
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  servlet:
    context-path: /g24
  port: 8080

DEEPSEEK_URL: https://api.deepseek.com/v1/chat/completions
DEEPSEEK_API_KEY: sk-ffe8a7cee4264152ab9c3ffe790600ef

jwt:
  secret: m365DpXCq3NQT/ZkODvhV0PKpRIGTcwRHpjUwPSh2U4=
  expiration: 3600000
