server.port=8080
# App & Server
spring.application.name=g24
server.servlet.context-path=/g24

# Database (use environment variables)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.initialization-mode=always
spring.jpa.hibernate.ddl-auto=none

# 5 minutes
spring.datasource.hikari.maxLifetime=700000
spring.datasource.hikari.maximumPoolSize=10
spring.datasource.hikari.connectionTimeout=30000

# SQL Logging (optional)
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# File upload
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# External API (DeepSeek) - use env variables
DEEPSEEK_URL=${DEEPSEEK_URL}
DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}

# JWT - use env variables
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

# Mail (local/dev, can disable in production)
spring.mail.host=${SPRING_SMTP_HOST}
spring.mail.port=${SPRING_SMTP_PORT}
spring.mail.username=${SPRING_MAIL_USERNAME}
spring.mail.password=${SPRING_MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.from=${SPRING_MAIL_FROM}

# application.properties
logging.file.name=/app/logs/g24.log
logging.file.max-size=10MB
logging.level.root=INFO
#Health Actuator
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info